baseURL = 'https://expidusos.com/'
copyright = '© Midstall Software & Contributors'
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = true
languageCode = 'en-us'
title = 'ExpidusOS'
titlecasestyle = 'Go'

[[module.imports]]
path = 'github.com/willfaught/paige'

[paige]
color = '#24283b'

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
noClasses = false
