languageName = 'English'
contentDir = 'content/en'

[[menu.main]]
identifier = 'home'
name = 'Home'
url = '/en/'
weight = 10

[[menu.main]]
identifier = 'download'
name = 'Download'
url = '/en/download'
weight = 20

[[menu.main]]
identifier = 'about'
name = 'About'
url = '/en/about'
weight = 30

[[menu.main]]
identifier = 'applications'
name = 'Applications'
url = '/en/applications'
weight = 40
