project_id: '579045'
api_token: CROWDIN_PERSONAL_TOKEN
base_path: .
base_url: 'https://api.crowdin.com'
preserve_hierarchy: 1
files:
  - source: /i18n/en.yaml
    translation: /i18n/%two_letters_code%.yaml
