FROM cirrusci/flutter:latest

WORKDIR /build
COPY pubspec.yaml ./
COPY l10n.yaml ./
COPY assets ./assets
COPY lib ./lib
COPY test ./test
COPY web ./web
RUN flutter build web
COPY deploy/lighttpd.dev.conf /lighttpd.conf
RUN sudo apt-get update \
  && sudo apt-get install -y lighttpd \
  && sudo rm -rf /var/lib/apt/lists/*

EXPOSE 80
RUN lighttpd -tt -f /lighttpd.conf
ENTRYPOINT ["lighttpd", "-D", "-f", "/lighttpd.conf"]
