name: (api) ESLint
on: [push]

defaults:
  run:
      working-directory: ./packages/api

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '14'
      - run: npm ci
      - run: npm run lint
