name: CI
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          cache: true
          channel: stable
      - name: Download dependencies
        run: |
          flutter pub get
      - name: Build
        run:
          flutter build web
      - if: ${{ github.event_name == 'push' }}
        name: Deploy
        run: |
          git config --global user.name "$(git --no-pager log --format=format:'%an' -n 1)"
          git config --global user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          cd build/web
          git init
          git branch -m gh-pages
          git add .
          git commit -a -m "Deploy ${{ github.sha }}"
          git push --force -u "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/${{ github.repository }}.git" gh-pages
